config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  root 'home#index'
  resources :jobs, only:[:show, :new, :create, :edit, :update]
  resources :companies, only:[:new, :create, :show, :edit, :update]
  resources :categories, only:[:show, :new, :create]
#  resources :categories, only:
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
  validates :name, presence: true

  before_action :authenticate_company!

  def premium?
    jobs.count >= 5
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  belongs_to :category

  DAYS_TO_EXPIRE = 90

  validates :title, :location, :description, :category, presence: true


  def expired?
    created_at < DAYS_TO_EXPIRE.days.ago
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  include Devise::TestHelpers

  def new
    @company = Company.new
  end

  def create
    @company = Company.new company_params

    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def show
    @company = Company.find(params[:id])

  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to @company
    else
      @company = Company.find(params[:id])
      render 'edit'
    end
  end


  private
  def company_params
    params.require(:company).permit(:name,
                                    :mail,
                                    :phone,
                                    :location)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.all
    @companies = Company.all
    @categories = Category.all

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_collections, only: [:new, :edit]
  before_action :find_job, only: [:show, :edit, :update]

  def index

  end
  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new job_params

    if @job.save
      redirect_to @job
    else
      set_collections
      render 'new'
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      set_collections
      render 'edit'
    end
  end

  private
  def job_params
    params.require(:job).permit(:title, :category_id, :company_id, :description,
                                :location, :featured)
  end

  def set_collections
    @companies = Company.all
    @categories = Category.all
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  Nome da categoria está em branco
<% end %>
<section>
  <%= simple_form_for @category do |f| %>
    <div>
      <%= f.input :name, label: 'Nome' %>
    </div>
    <div>
      <%= f.submit 'Criar Categoria' %>
    </div>
  <% end %>
</section>

app/views/categories/show.html.erb
<div class="row">
  <section class="category">
    <div class="col-md-10">
      <h1> <%= @category.name %> </h1>
    </div>
  </section>
  <aside id="jobs">
    <div class = "col-md-2">
      <div class="row">
        <% if @category.jobs.empty? %>
          <strong> Nenhuma vaga disponível </strong>
        <% end %>
        <% @category.jobs.each do |job| %>
            <%= render job %>
        <%end%>
      </div>
    </div>
  </aside>

</div>

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
  <%= label_error %>
<% end %>
<section>
<%= simple_form_for @company do |f| %>
  <div class="form-group">
    <%= f.input :name, label: 'Nome', class: "form-control",  autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.input :location, label: 'Local'%>
  </div>
  <div class="form-group">
    <%= f.input :mail, label: 'Email' %>
  </div>
  <div class="form-group">
    <%= f.input :phone, label: 'Telefone' %>
  </div>
  <div>
    <%= f.submit submit_text %>
  </div>
<% end %>
</section>

app/views/companies/edit.html.erb
<section>
  <%= render partial: 'form',
      locals: {submit_text: 'Atualizar Empresa'} %>

</section>

app/views/companies/new.html.erb
<section>
  <h1> New Company </h1>
  <%= render partial: 'form',
  locals: {submit_text: 'Criar Empresa',
          label_error: 'Não foi possível criar a Empresa'} %>
</section>

app/views/companies/show.html.erb
<div class="row">
  <section class="company">
    <div class="col-md-10">
      <h1> <%= @company.name %> </h1>
      <%= link_to  'Editar', edit_company_path %><br>
      <%= @company.premium? ? (image_tag 'estrela.jpg') : ''   %>
      <%= @company.location %><br>
      <%= @company.mail %> <br>
      <%= @company.phone %> <br>
    </div>
  </section>
  <aside id="jobs">
    <div class = "col-md-2">
      <div class="row">
        <% if @company.jobs.empty? %>
          <strong> Nenhuma vaga disponível </strong>
        <% end %>
        <% @company.jobs.each do |job| %>
            <%= render job %>
        <%end%>
      </div>
    </div>
  </aside>

</div>

app/views/home/index.html.erb
<div class = "row">
  <div class="col-md-9">
    <section id="jobs">
      <div class="row">
        <% @jobs.each do |job| %>
          <div class="col-md-6">
            <%= render job %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
  <div class = "col-md-3">
    <aside>
      <h1> Empresas </h1>
      <% @companies.each do |company| %>
        <%= link_to company.name, company %><p>
      <% end %>
      <br>
      <h1> Categorias </h1>
      <% @categories.each do |category| %>
        <%= link_to category.name, category %><p>
      <% end %>
    </aside>
  </div>
</div>

app/views/jobs/_form.html.erb
<% if @job.errors.any? %>
  <%= label_error %>
<% end %>
<section>
  <%= simple_form_for @job, {html: {class: "form-horizontal"}} do |f| %>
    <div class="form-group">
      <%= f.input :title, label: 'Título', class: "form-control",  autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.input :location, label: 'Local' %>
    </div>
    <div class="form-group">
      <%= f.association :category, label: 'Categoria' %>
    </div>
    <div class="form-group">
      <%= f.association :company, label: 'Empresa' %>
    </div>
    <div class="form-group">
      <%= f.input :description, as: :text, label: 'Descrição' %>
    </div>
    <div class="checkbox">
      <%= f.input :featured, label: 'Destaque' %>
    </div>
    <div>
        <%= f.submit submit_text %>
    </div>
  <% end %>
</section>

app/views/jobs/_job.html.erb
<% unless job.expired? %>
  <h1> <%= link_to job.title, job %> </h1>
  <p>
    <% if job.featured? %>
      <strong> Destaque </strong><br>
    <% end %>
    <%= job.category.name %><br>
    <%= job.company.name %><br>
    <%= job.location %><br>
  </p>
<% end %>

app/views/jobs/edit.html.erb
<section>

  <%= render partial: 'form',
      locals: {submit_text: 'Atualizar Vaga',
              label_error: 'Não foi possível atualizar a vaga'} %>
</section>

app/views/jobs/new.html.erb
<section>
  <h1> New Job </h1>
  <%= render partial: 'form',
      locals: {submit_text: 'Criar Vaga',
              label_error: 'Não foi possível criar a vaga'} %>

</section>

app/views/jobs/show.html.erb
<section>
  <div>
      <% if @job.expired? %>
        <%= 'Vaga Expirada' %>
      <% end %>
      <p>
        <h1> <%= @job.title %> </h1>
        <%= link_to  'Editar', edit_job_path %><br>
        <% if @job.featured? %>
          <strong> Destaque </strong> <br>
        <% end %>
        <%= @job.category.name %><br>
        <%= @job.company.name %><br>

        <%= @job.description %><br>
        <%= @job.location %><br>
      </p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpregoJa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <div class="btn-toolbar" role="toolbar" aria-label="...">
          <%= link_to 'Voltar Pagina inicial', root_path,
                        class: "btn btn-default" %>
          <%= link_to 'Nova vaga', new_job_path,
                        class: "btn btn-default" %>
          <%= link_to 'Nova Empresa', new_company_path,
                        class: "btn btn-default" %>
          <%= link_to 'Nova Categoria', new_category_path,
                        class: "btn btn-default" %>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <h1>Emprego Já </h1>
      <%= yield %>
    </div>
  </body>
</html>